# -*- coding: utf-8 -*-
"""04_model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjCxwdzmwuN13nBWsIFqJQhVDt4zbiei
"""

import pandas as pd
import numpy as np

"""### STEP 1: Setup + Load Feature Data"""

# Load feature datasets for model training

X_placement = pd.read_csv("data/cleaned/placement_features.csv")
y_placement = pd.read_csv("data/cleaned/placement_target.csv")

X_salary = pd.read_csv("data/cleaned/salary_features.csv")
y_salary = pd.read_csv("data/cleaned/salary_target.csv")

print("Placement data shape:", X_placement.shape, y_placement.shape)
print("Salary data shape:", X_salary.shape, y_salary.shape)

"""### STEP 2: Train–Test Split + Preprocessing Pipeline"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# ---------- SPLIT ----------

X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(
    X_placement, y_placement, test_size=0.2, random_state=42, stratify=y_placement
)

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    X_salary, y_salary, test_size=0.2, random_state=42
)

# ---------- PREPROCESSING ----------

# Identify column types automatically
categorical_cols_p = X_train_p.select_dtypes(include=['object', 'category']).columns.tolist()
numeric_cols_p = X_train_p.select_dtypes(exclude=['object', 'category']).columns.tolist()

categorical_cols_s = X_train_s.select_dtypes(include=['object', 'category']).columns.tolist()
numeric_cols_s = X_train_s.select_dtypes(exclude=['object', 'category']).columns.tolist()

# Preprocessors
preprocess_p = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_cols_p),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols_p)
    ]
)

preprocess_s = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_cols_s),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols_s)
    ]
)

print("Placement split:", X_train_p.shape, X_test_p.shape)
print("Salary split:", X_train_s.shape, X_test_s.shape)
print("Placement categorical cols:", categorical_cols_p)
print("Salary categorical cols:", categorical_cols_s)

"""### STEP 3: Placement Model – Baseline (Logistic Regression)"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

# ---------- PIPELINE WITH LOGISTIC REGRESSION ----------

placement_model = Pipeline(steps=[
    ('preprocess', preprocess_p),
    ('model', LogisticRegression(max_iter=1000, class_weight='balanced'))
])

# Train model
placement_model.fit(X_train_p, y_train_p.values.ravel())

# Predictions
y_pred_p = placement_model.predict(X_test_p)
y_prob_p = placement_model.predict_proba(X_test_p)[:, 1]

# Evaluation
print("Accuracy:", accuracy_score(y_test_p, y_pred_p))
print("\nClassification Report:\n", classification_report(y_test_p, y_pred_p))
print("ROC-AUC:", roc_auc_score(y_test_p, y_prob_p))

"""### STEP 4: Advanced Placement Model (Random Forest)"""

from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline(steps=[
    ('preprocess', preprocess_p),
    ('model', RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        random_state=42,
        class_weight='balanced'
    ))
])

# Train
rf_model.fit(X_train_p, y_train_p.values.ravel())

# Predict
y_pred_rf = rf_model.predict(X_test_p)
y_prob_rf = rf_model.predict_proba(X_test_p)[:, 1]

# Evaluate
print("Random Forest Accuracy:", accuracy_score(y_test_p, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test_p, y_pred_rf))
print("ROC-AUC:", roc_auc_score(y_test_p, y_prob_rf))

"""### STEP 5: Salary Model – Baseline (Linear Regression)"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# ---------- LINEAR REGRESSION PIPELINE ----------

salary_lr_model = Pipeline(steps=[
    ('preprocess', preprocess_s),
    ('model', LinearRegression())
])

# Train
salary_lr_model.fit(X_train_s, y_train_s.values.ravel())

# Predict
y_pred_s = salary_lr_model.predict(X_test_s)

# Evaluation
rmse = np.sqrt(mean_squared_error(y_test_s, y_pred_s))
mae = mean_absolute_error(y_test_s, y_pred_s)
r2 = r2_score(y_test_s, y_pred_s)

print("Salary Model (Linear Regression)")
print("RMSE:", rmse)
print("MAE:", mae)
print("R² Score:", r2)

"""### STEP 6: Advanced Salary Model (Random Forest Regressor)"""

from sklearn.ensemble import RandomForestRegressor

salary_rf_model = Pipeline(steps=[
    ('preprocess', preprocess_s),
    ('model', RandomForestRegressor(
        n_estimators=200,
        max_depth=12,
        random_state=42
    ))
])

# Train
salary_rf_model.fit(X_train_s, y_train_s.values.ravel())

# Predict
y_pred_rf_s = salary_rf_model.predict(X_test_s)

# Evaluation
rmse_rf = np.sqrt(mean_squared_error(y_test_s, y_pred_rf_s))
mae_rf = mean_absolute_error(y_test_s, y_pred_rf_s)
r2_rf = r2_score(y_test_s, y_pred_rf_s)

print("Salary Model (Random Forest)")
print("RMSE:", rmse_rf)
print("MAE:", mae_rf)
print("R² Score:", r2_rf)

"""### STEP 7: SAVE FINAL MODELS"""

import os
import joblib

# Create models directory in Colab local storage
MODELS_PATH = "models/"
os.makedirs(MODELS_PATH, exist_ok=True)

# Save models locally in Colab
joblib.dump(placement_model, MODELS_PATH + "placement_model.pkl")
joblib.dump(salary_rf_model, MODELS_PATH + "salary_model.pkl")

print("Models saved successfully!")
print("Files in /content/models:")
print(os.listdir(MODELS_PATH))

