# -*- coding: utf-8 -*-
"""06_startup_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HobSa3RA3EHV92T_Co2irX47N7rVCBa4
"""

# =========================================
# 06_startup_model.ipynb
# Cell 1: Load Processed Data
# =========================================

import joblib

X_train = joblib.load("data/processed/startup_X_train_enc.pkl")
X_test  = joblib.load("data/processed/startup_X_test_enc.pkl")
y_train = joblib.load("data/processed/startup_y_train.pkl")
y_test  = joblib.load("data/processed/startup_y_test.pkl")

print("Data loaded successfully")
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

# =========================================
# Cell 2: Train & Evaluate Startup Risk Model
# =========================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Initialize model
startup_risk_model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

# Train model
startup_risk_model.fit(X_train, y_train)

# Predict
y_pred = startup_risk_model.predict(X_test)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)

print("📊 Model Accuracy:", accuracy)
print("\n📄 Classification Report:\n")
print(classification_report(y_test, y_pred))

# =========================================
# Cell 3: Save Startup Risk Model (Colab)
# =========================================

import os
import joblib

# Create models directory if not exists
os.makedirs("/content/models", exist_ok=True)

# Save trained model
joblib.dump(startup_risk_model, "models/startup_risk_model.pkl")

print("✅ Startup Risk model saved successfully!")
print("Saved at: /content/models/startup_risk_model.pkl")

